name: CFF Author Updater
description: Add GitHub and raw commit authors to the authors section of CITATION.cff and post a pull request comment with updated CFF and qualifying contributions from new authors.

inputs:
  github_token:
    description: GitHub token for API access
    required: true
    type: string
  base_branch:
    description: The base branch to compare against (target of PR)
    required: true
    type: string
  head_branch:
    description: The head branch (source of PR)
    required: true
    type: string
  cff_path:
    description: Path to the CFF file (default is CITATION.cff)
    required: false
    type: string
    default: CITATION.cff
  post_pr_comment:
    description: Whether to post a pull request comment (true/false)
    required: false
    type: boolean
    default: true
  authorship_for_pr_commits:
    description: Include PR commit authors and co-authors as authors
    required: false
    type: boolean
    default: true
  authorship_for_pr_reviews:
    description: Include PR reviewers as authors
    required: false
    type: boolean
    default: true
  authorship_for_pr_issues:
    description: Include creators of issues linked to the PR as authors
    required: false
    type: boolean
    default: true
  authorship_for_pr_issue_comments:
    description: Include commenters on linked issues as authors
    required: false
    type: boolean
    default: true
  authorship_for_pr_comments:
    description: Include users who comment directly on the PR as authors
    required: false
    type: boolean
    default: true
  missing_author_invalidates_pr:
    description: Invalidate pull request if a new author is missing from the CFF file
    type: boolean
    default: true
  duplicate_author_invalidates_pr:
    description: Invalidate the pull request if there is a duplicate author in the CFF file
    type: boolean
    default: true
  invalid_cff_invalidates_pr:
    description: Invalidate the pull request if cffconvert fails to validate the CFF file
    type: boolean
    default: true
  can_skip_authorship:
    description: Whether manually skipping and unskipping authorship is enabled or not
    type: boolean
    default: true
  bot_blacklist:
    description: 'Comma-separated list of bot usernames to ignore'
    required: false
    default: 'github-actions[bot]'

outputs:
  new_authors:
    description: New authors and qualifying contributions in JSON
  original_cff:
    description: Full original CFF content in YAML
  original_cff_is_valid_cff:
    description: Whether the original CFF file has valid CFF according to cffconvert ('true' or 'false')
  updated_cff:
    description: Full updated CFF content in YAML. If no changes, this will be the same as the original CFF file.
  updated_cff_is_valid_cff:
    description: Whether the updated CFF file has valid CFF according to cffconvert ('true' or 'false')
  updated_cff_has_error:
    description: Whether the updated CFF file has an error ('true' or 'false'). An error invalidates the pull request.
  updated_cff_has_warning:
    description: Whether the updated CFF file has an error ('true' or 'false'). A warning does not invalidate the pull request.
  error_log:
    description: Log that contains errors about the CFF author update process.
  warning_log:
    description: Log that contains warnings about the CFF author update process.
  info_log:
    description: Log that contains general information about the CFF author update process.

runs:
  using: "composite"
  steps:

    - name: Install action with pip
      run: pip install --force-reinstall ${{ github.action_path }} # the --force-reinstall avoids caching issues from external dependencies which may rely on this action
      shell: bash

    - name: Update CFF authors
      id: update_cff_authors
      run: cff-author-updater
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ github.repository }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        HEAD_BRANCH: ${{ inputs.head_branch }}
        CFF_PATH: ${{ inputs.cff_path }}
        POST_PR_COMMENT: ${{ inputs.post_pr_comment }}
        AUTHORSHIP_FOR_PR_COMMITS: ${{ inputs.authorship_for_pr_commits }}
        AUTHORSHIP_FOR_PR_REVIEWS: ${{ inputs.authorship_for_pr_reviews }}
        AUTHORSHIP_FOR_PR_ISSUES: ${{ inputs.authorship_for_pr_issues }}
        AUTHORSHIP_FOR_PR_ISSUE_COMMENTS: ${{ inputs.authorship_for_pr_issue_comments }}
        AUTHORSHIP_FOR_PR_COMMENTS: ${{ inputs.authorship_for_pr_comments }}
        MISSING_AUTHOR_INVALIDATES_PR: ${{ inputs.missing_author_invalidates_pr }}
        DUPLICATE_AUTHOR_INVALIDATES_PR: ${{ inputs.duplicate_author_invalidates_pr }}
        INVALID_CFF_INVALIDATES_PR: ${{ inputs.invalid_cff_invalidates_pr }}
        CAN_SKIP_AUTHORSHIP: ${{ inputs.can_skip_authorship }}
        BOT_BLACKLIST: ${{ inputs.bot_blacklist }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
